### ISSUE TITLE
Change in v.1.1.2 not working

### ISSUE THREAD

**Issue by danielalvsaaker** [0nse/mopidy-scrobbler#1]
I installed this fork to fix the multiple artists scrobbling issue, but the error persists. Did I install the wrong way? I used `pip install git+git://github.com/0nse/mopidy-scrobbler` to install. Is there a way for me to fix this?

**Comment by 0nse** [comment]
I haven't used Mopidy in over a year or so. Thus, I'm unsure whether this extension is still working with the most recent Mopidy updates.

Have you verified, that my fork had actually overwritten any previously installed versions of [mopidy/mopidy-scrobbler](https://github.com/mopidy/mopidy-scrobbler/)?

 > "but the error persists"

Meaning that the extension is scrobbling but is still using those ugly merged album artists?

**Comment by danielalvsaaker** [comment]
Yep. Still those ugly merged album artists. 
I am not sure how to correctly check if mopidy-scrobbler has been properly overwritten. But I tried to uninstall before installing your fork, with no success.

Thank you so much for replying, by the way.

**Comment by 0nse** [comment]
You're welcome.

The install location varies depending on your installed Python version and OS/distribution. For me as an Arch Linux user, [`mopidy-scrobbler` is installed to `/usr/lib/python2.7/site-packages/mopidy_scrobbler/`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mopidy-scrobbler).

If you can make out this directory on your PC, you can manually overwrite the contents with my fork.

**Comment by danielalvsaaker** [comment]
```
ERROR    Failed to load extension scrobbler: name 'registry' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/ext.py", line 202, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/mopidy_scrobbler/__init__.py", line 33, in <module>
    registry.add('frontend', ScrobblerFrontend)
NameError: name 'registry' is not defined
```
After applying your changes, this error pops up when starting mopidy in terminal. What did I forget?

**Comment by 0nse** [comment]
I just started Mopidy and scrobbling works for me:
```
WARNING  The Libre.fm session key does not exist. A Web browser will open an authentication URL. Confirm access using your username and password. This has to be done only once.               
INFO     A Web browser may not be opened if you run Mopidy as a different user. In this case, you will have to manually open the link "<SCRUBBED/>".                                           
INFO     Finished refreshing Google Music library in 16s                                                                                                                                       
INFO     Loaded 9 playlists from Google Music                                                                                                                                                  
INFO     Finished refreshing Google Music playlists in 29s                                                                                                                                     
INFO     Scrobbler connected to Libre.fm   
```
![scrobbling](https://i.imgur.com/VPbA4v2.png)

---

What versions are you using? I have
* Mopidy 2.1.0
* mopidy-scrobbler 1.2.0 with [this patch](https://github.com/mopidy/mopidy-scrobbler/issues/20#issuecomment-208032286) applied. However, this patch shouldn't affect this extension's startup.

---

Your error seems odd to me, as the lines containing the missing `registry` parameter have been untouched for 4 years now. I also just checked [ext.py](https://github.com/mopidy/mopidy/blob/develop/mopidy/ext.py#L128) which still has the `registry` parameter in the `setup` method signature.

---

Did you add the `[scrobbler]` section to your config including all four parameters?

**Comment by danielalvsaaker** [comment]
I'm definitely using the same versions as you, all four parameters are also included in my config.

**Comment by 0nse** [comment]
This really confuses me. Have you made sure that it is not a caching problem by removing any previously compiled files?
```bash
rm /usr/lib/python2.7/site-packages/mopidy_scrobbler/*.py{c,o}
```
Currently, I have no idea other than that…

**Comment by danielalvsaaker** [comment]
That did remove two files but it didn't seem to fix it... Thank you very much, even though!

**Comment by danielalvsaaker** [comment]
I seem to have fixed it! I still fail to understand why the "registry not defined" issue happened, but I figured that if i specified pip install with `pip install github link -t /usr/lib/python2.7/site-packages`, mopidy-scrobbler would properly install.
